name: Auto Tag - Creation

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter Preferred Tag(Eg: v1.0.0) or It picks from pom.xml'
        required: false
      tagdescription:
        description: 'Enter Tag Description'
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
    - uses: actions/checkout@v3
    - name: Auto Tag Creation
      if: inputs.tag == ''
      uses: butlerlogic/action-autotag@stable
      with:
        strategy: regex
        root: "./pom.xml"
        regex_pattern: "<version>(.+?)</version>"
        tag_message: ${{inputs.tagdescription}}
      env:
        GITHUB_TOKEN: "${{ github.token }}"

    - name: Custom Tag Creation
      if: inputs.tag != ''
      uses: rickstaa/action-create-tag@v1
      with:
        message: ${{inputs.tagdescription}}
        tag: ${{inputs.tag}}
      env:
        GITHUB_TOKEN: "${{ github.token }}"