name: Sample Environments Deploy

on:
  workflow_dispatch:

jobs:
  devdeployment:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Dev Deploy
	  - run: |
	    echo "Dev Deployments"

	  